version: '3'
services:
  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:5.6.8
    ports:
      - "9200:9200"
      - "9300:9300" 
    environment:
      - cluster.name=docker-cluster-nave
      - bootstrap.memory_lock=true
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
      - xpack.security.enabled=false
      - discovery.type=single-node
    ulimits:
      memlock:
        soft: -1
        hard: -1
  fuseki:
    image: stain/jena-fuseki:latest
    ports:
      - "3030:3030"
    environment:
      - ADMIN_PASSWORD=pw123
  postgresql:
    image: mdillon/postgis:9.3
    restart: always
    ports:
      - "5432:5432"
    environment:
      POSTGRES_PASSWORD: pw123
