# -*- coding: utf-8 -*-
# Generated by Django 1.10.8 on 2021-09-28 10:45
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('virtual_collection', '0002_auto_20160606_1441'),
    ]

    operations = [
        migrations.CreateModel(
            name='VirtualCollectionOrQuery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('query', models.TextField(blank=True, help_text='Additional or queries', null=True, verbose_name='query')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Position')),
                ('diw', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orqueries', to='virtual_collection.VirtualCollection')),
            ],
            options={
                'verbose_name': 'Or Query',
                'verbose_name_plural': 'Or Queries',
                'ordering': ['position'],
            },
        ),
    ]
