# -*- coding: utf-8 -*-
# Generated by Django 1.10.5 on 2017-02-26 19:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lod', '0012_auto_20161115_0100'),
    ]

    operations = [
        migrations.AddField(
            model_name='cacheresource',
            name='allow_linked_open_data',
            field=models.BooleanField(default=True, verbose_name='Allow Linked Open Data'),
        ),
        migrations.AddField(
            model_name='rdfmodeltest',
            name='allow_linked_open_data',
            field=models.BooleanField(default=True, verbose_name='Allow Linked Open Data'),
        ),
    ]
