# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 13:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0012_remove_dataset_excluded_index_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='edmrecord',
            name='allow_linked_open_data',
            field=models.BooleanField(default=True, verbose_name='Allow Linked Open Data'),
        ),
    ]
