# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-28 14:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0013_edmrecord_allow_linked_open_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='name',
            field=models.CharField(blank=True, max_length=512, null=True, verbose_name='title'),
        ),
    ]
