# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2018-02-20 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('void', '0014_auto_20170628_1602'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataset',
            name='description',
            field=models.TextField(blank=True, null=True, verbose_name='description'),
        ),
        migrations.AlterField(
            model_name='proxymapping',
            name='proxy_resource_uri',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='proxymapping',
            name='skos_concept_uri',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='proxyresource',
            name='proxy_uri',
            field=models.URLField(max_length=2000, unique=True),
        ),
        migrations.AlterField(
            model_name='proxyresourcefield',
            name='dataset_uri',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='proxyresourcefield',
            name='property_uri',
            field=models.URLField(max_length=2000),
        ),
        migrations.AlterField(
            model_name='proxyresourcefield',
            name='search_label',
            field=models.CharField(max_length=500),
        ),
    ]
